### ISSUE TITLE
Second Mastery Not Showing (Immortal Throne cd-version)

### ISSUE THREAD

**Issue by Rinqium** [epinter/tqrespec#28] opened 2020-10-15 05:01 UTC
I play the game from a CD download. When I attempt to change my masteries, one of them do not appear (Of course the one I want to change. Lol). Let me know if you need further information.
![Attributes](https://user-images.githubusercontent.com/63993076/96078883-b4f4cc00-0e70-11eb-97fe-7d5a4779d77e.JPG)
![Skills](https://user-images.githubusercontent.com/63993076/96078884-b58d6280-0e70-11eb-929c-c3900ff99b20.JPG)

**Comment by epinter** [comment] 2020-10-15 15:31
Do you see this behaviour with other characters ?
Can you send me the player.chr and the file %TEMP%/tqrespec.log ?
I need to know the Titan Quest version and DLCs installed.

**Comment by Rinqium** [comment] 2020-10-15 21:43
I do not have another character to test for a repeat in the issue. Would you like to speed run up to two masteries and test it out?
I think I found the player.chr file you are referring to. It was under the "SaveData" file.
I am unable to find the %TEMP%/tqrespec.log file. Where should that be located?
[Player.zip](https://github.com/epinter/tqrespec/files/5388047/Player.zip)

**Comment by epinter** [comment] 2020-10-16 21:07
I will try your player.chr. For now, there's no need to provide another character... The log is empty, no errors. Just as a double check, when you have some time run TQRespec again, select the skills tab and try the remove skills buttons (without save), just to see if an error is sent to log.

**Comment by Rinqium** [comment] 2020-10-16 22:45
I ran TQRespec again, I selected the skills tab and clicked the remove skills button and did not save. I will attach the log file again. I think I'm getting the right file.
Log file location: "C:\Users\Lynn\AppData\Local\Temp\*FILE*"
The file shows no applicable errors, which makes sense to me. The Dream mastery on the left seems to works perfectly. However, I am unable to see or work on the Hunter mastery on the right side.
Sorry I forgot to answer this question before. I am running Immortal Thrones version of the game. I play it off of a CD I bought back in about 2006. Honestly I'm surprised TQRespec even worked on CD-ROM version (As I understand TQRespec was built for the Steam version of the game).
[tqrespec.zip](https://github.com/epinter/tqrespec/files/5394587/tqrespec.zip)

**Comment by epinter** [comment] 2020-10-16 23:11
The log file location is correct.
I tried to support every version since Immortal Throne, but for some reason recent updates made the masteries and skills information load incorrectly with TQIT. I will try to install TQIT cd version and reproduce the problem properly.

Thanks for your help. I will reply here as soon as I have a solution.

**Comment by Rinqium** [comment] 2020-10-16 23:28
No, thank you for your help. I will wait for your reply.
Just so you know.  For my cd version I had to put in the TEXT folder and Text_EN.arc file in my Titan Quest Immortal Thrones Program Files (x86) folder in order to get TQRespec to boot up.

**Comment by epinter** [comment] 2020-10-22 17:18
Hi. Can you try this build ?

https://1drv.ms/u/s!Al6bs7S_f0Jth3I1O3wrQLO1tNoJ?e=g3I9y6

**Comment by Rinqium** [comment] 2020-10-22 19:22
Still experiencing the same issue.
![Capture](https://user-images.githubusercontent.com/63993076/96919808-8a56d480-1469-11eb-9af1-bdeaf9b55f1a.JPG)

**Comment by epinter** [comment] 2020-10-22 19:37
Did you remove the "text" folder you had to put in TQIT folder days ago ? What message you have in the tqrespec.log ?

I have the disc-version installed, with this layout:

TQ:
Titan Quest/Database/database.arz
Titan Quest/Text/Text_EN.arc
Titan Quest/Titan Quest.exe

TQIT:
Titan Quest Immortal Throne/Database/database.arz
Titan Quest Immortal Throne/Resources/Text_EN.arc
Titan Quest Immortal Throne/Tqit.exe

In my tests TQIT and TQ directories are detected, and both databases and text resources are loaded.

**Comment by Rinqium** [comment] 2020-10-22 19:49
I have not removed the "Text" folder and file I got from online. Should I remove them and try again? Could that be causing the issue if I have the wrong text file?

The tqrespec.log file says the following...
Oct 14, 2020 10:09:45 PM br.com.pinter.tqrespec.core.SingleInstanceLock deleteLock
SEVERE: Error deleting lockfile 'C:\Users\Lynn\AppData\Local\Temp\tqrespec.pid'

The layout of my TQ & TQIT is a little more complex. I will include screenshots bellow.
![TQ](https://user-images.githubusercontent.com/63993076/96922626-54b3ea80-146d-11eb-9726-9602f0090dea.JPG)
![TQIT](https://user-images.githubusercontent.com/63993076/96922630-554c8100-146d-11eb-8829-4d2a3ba27e8a.JPG)

**Comment by epinter** [comment] 2020-10-22 20:53
Talking abount the disc-version, as far as I know, the Text_EN.arc of TQIT should be inside Resources/, and the Text_EN.arc of TQ is inside Text/. The text_en.arc in a wrong directory will make the detection fail.

The build I sent to you writes these lines in my log:
INFO: Using databases '[D:\temp\tq\Database\database.arz, D:\temp\tqit\Database\database.arz]'
Oct 22, 2020 5:05:08 PM br.com.pinter.tqrespec.tqdata.GameInfo searchGamepathResources
INFO: Using text '[D:\temp\tq\Text, D:\temp\tqit\Resources]'


When TQRespec starts, it saves the last used directory in the windows registry (HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\br\com\pinter\tqrespec), key "last_detectedgamepath". If you didn't change the TQIT directory, there's no need to touch this key. This information is removed automatically by TQRespec if this path is invalid.

Try to delete the log and run tqrespec again to see if the messages above appears.

**Comment by Rinqium** [comment] 2020-10-23 02:11
Sure enough, the Text_EN.arc file is in the resources folder for TQIT.
I removed the Text folder and file that I added to the TQIT folder, and tried running TQRespec again and now it works!

Do you still want me to check the log file for you? If so, you might need to re-explain what you'd like me to do. I couldn't quiet follow your instructions above.

**Comment by epinter** [comment] 2020-10-23 12:45
If it worked, there's no need to check the log, I already have all the information I need. I will make some minor changes and publish these new fixes. Thank you!

**Comment by epinter** [comment] 2020-10-26 00:47
Hi, can you do a last test for me when you have some time ? I changed the game detection logic, and need to be sure it's working...

https://1drv.ms/u/s!Al6bs7S_f0Jth3SjPKS1o63HwQT2?e=aEN1G7

**Comment by Rinqium** [comment] 2020-10-28 00:29
Sorry for my late reply. I just tested it out and it works perfectly. Thank you for all your help!

**Comment by epinter** [comment] 2020-10-28 17:46
Thanks!

**Comment by epinter** [comment] 2020-10-31 22:06
Fixed in release v0.8.2.

**Closed by epinter** 2020-10-31 22:06 UTC
Labels: bug
